### ISSUE TITLE
Issues importing data from a relative path

### ISSUE THREAD

**Issue by Xe** [philandstuff/dhall-golang#2]
I've been experimenting with integrating this package into a project of mine and I've run into an issue. Here's the [git repo](https://tulpa.dev/cadey/mi/src/branch/dhall). I tried to use the following Go code:

```go
package main

import (
	"io/ioutil"

	"github.com/kr/pretty"
	"github.com/philandstuff/dhall-golang"
)

type Config struct {
	Discord struct {
		Webhook string `json:"Webhook"`
	} `json:"Discord"`
	Gitea struct {
		Instance string `json:"Instance"`
		Token    string `json:"Token"`
	} `json:"Gitea"`
	Github struct {
		Token string `json:"Token"`
	} `json:"Github"`
	Mastodon struct {
		Account   string `json:"Account"`
		AppID     string `json:"AppID"`
		AppSecret string `json:"AppSecret"`
		Instance  string `json:"Instance"`
		Token     string `json:"Token"`
	} `json:"Mastodon"`
	Paseto struct {
		Private string `json:"Private"`
		Public  string `json:"Public"`
	} `json:"Paseto"`
	Patreon struct {
		AccessToken  string `json:"AccessToken"`
		ClientID     string `json:"ClientID"`
		ClientSecret string `json:"ClientSecret"`
		RefreshToken string `json:"RefreshToken"`
	} `json:"Patreon"`
	Reddit struct {
		AppID     string `json:"AppID"`
		AppSecret string `json:"AppSecret"`
		Password  string `json:"Password"`
		Username  string `json:"Username"`
	} `json:"Reddit"`
	RethinkDBURL string `json:"RethinkDBURL"`
	Twitter      struct {
		APIKey         string `json:"ApiKey"`
		APISecret      string `json:"ApiSecret"`
		ConsumerSecret string `json:"ConsumerSecret"`
		ConsumerToken  string `json:"ConsumerToken"`
	} `json:"Twitter"`
}

func main() {
	var cfg Config
	data, err := ioutil.ReadFile("mi.dhall")
	if err != nil {
		panic(err)
	}
	err = dhall.Unmarshal([]byte(data), &cfg)
	if err != nil {
		panic(err)
	}
	pretty.Println(cfg)
}
```

to import [this folder of dhall files](https://tulpa.dev/cadey/mi/src/branch/dhall/cfg) via this expression:

```dhall
let mi = ./cfg/package.dhall in mi.Mi::{=}
```

but I get this error:

```console
$ go run ./cmd/mi-cfg/
panic: unknown term type./cfg/package.dhall

goroutine 1 [running]:
github.com/philandstuff/dhall-golang/core.evalWith(0x7f6224428110, 0xc000116cc0, 0xc00039a7e0, 0x0, 0x0, 0x1)
        /home/cadey/go/pkg/mod/github.com/philandstuff/dhall-golang@v0.0.0-20200128213416-5ebf1681a323/core/eval.go:604 +0x7610
github.com/philandstuff/dhall-golang/core.evalWith(0x83eca0, 0xc00039a720, 0xc00039a7b0, 0x83ec00, 0xc00039a720, 0x1)
        /home/cadey/go/pkg/mod/github.com/philandstuff/dhall-golang@v0.0.0-20200128213416-5ebf1681a323/core/eval.go:128 +0x722a
github.com/philandstuff/dhall-golang/core.Eval(...)
        /home/cadey/go/pkg/mod/github.com/philandstuff/dhall-golang@v0.0.0-20200128213416-5ebf1681a323/core/eval.go:14
github.com/philandstuff/dhall-golang.Unmarshal(0xc0000f2000, 0x7b6, 0x9b6, 0x72f740, 0xc0000b6180, 0x0, 0x0)
        /home/cadey/go/pkg/mod/github.com/philandstuff/dhall-golang@v0.0.0-20200128213416-5ebf1681a323/unmarshal.go:34 +0xef
main.main()
        /home/cadey/code/mi/cmd/mi-cfg/main.go:59 +0xbe
exit status 2
```

I believe I am using the most recent version of the dhall-golang package [based on this commit](https://github.com/philandstuff/dhall-golang/commit/5ebf1681a323abc5692f5eca047ce8886b4933e3). Am I doing anything wrong or have I found a bug?

**Comment by philandstuff** [comment]
Oof, this is a silly bug in `dhall.Unmarshal` which doesn't currently resolve imports.  I'll work on a fix.
